// The Clemmer family tree: every person, relationship, source, notable event, place and
// map movement, plus the site's title, family lines and opening text. index.html draws
// it and holds no family data of its own. Edit here, then run `node tools/check.js`.

// ---------- The site ----------
// What the header says, and the opening card shown when nobody is selected.
// lede and intro may use <b> and <i>; nothing else.
const SITE = {
  title: "Clemmer",
  titleEm: "Family Tree",
  eyebrow: "Two lines, one family",
  heading: "From Point Marion and Smithfield",
  lede: "The Clemmers and the Dunhams lived a few miles apart in the southwest corner of Fayette County, Pennsylvania, along the West Virginia line. William Bryan Clemmer of Point Marion married Margaret Belle Dunham of Smithfield at Morgantown in 1938.",
  intro: [
    "The Clemmers were in Springhill Township by 1880, when Lebbeus Bigelow Clemmer, a brick molder, was raising six children there. His son Amadee clerked in a grocery store and died of tuberculosis in 1921, when his own son William was twelve. Margaret's parents, Martin Dunham and Emma Miller, raised a large family in Georges Township.",
    "Behind them the families reach back into Fayette County and across the line into Monongalia: Andrew Clemmer in Springhill by 1850, the Rumbles and Varners, the Wilkinses from Morgantown, the Dunhams and Dewalts, and the Millers.",
    "The tree is just begun. Every person carries the records behind what the card says, and links the records make likely but do not prove are marked as probable.",
  ],
};

// ---------- Family lines ----------
// Each line gets a column in the tree (x, a fraction of the width; xDirect for its people
// on the direct line) and a colour for light and dark themes. "other" (people who married
// in) is built in and needs no entry. Keys become CSS class names: lowercase letters and
// digits only.
//
// Colours carried over from the Millet tree, for lines added later:
//   brown ["#9C6C2E","#D4A45A"]  blue ["#3E6D8B","#7FB2D0"]  olive ["#6E6A3C","#B8B26A"]
//   plum  ["#8A4A60","#D48CA6"]  teal ["#2E7A78","#7CC8C4"]
const LINES = {
  clem: { name: "Clemmer", label: "Clemmer line", color: ["#9C6C2E", "#D4A45A"], x: 0.30, xDirect: 0.38 },
  dun: { name: "Dunham", label: "Dunham line", color: ["#3E6D8B", "#7FB2D0"], x: 0.72, xDirect: 0.62 },
};

// ---------- Sources ----------
// Keyed by a short name: [citation, link]. Define a source before the people who cite it.
const FS = "https://www.familysearch.org/ark:/61903/1:1:";
const S = {
  family: ["Family knowledge: April Millet (née Clemmer), 2026", ""],
  cen1910: ["1910 census, Springhill Twp., Fayette Co., Pa., sheet 6A: A. H. Clemmer, 30, with wife Eliza, 26, son Wm, 2, and daughter Grace", FS + "MG3H-Y2D"],
  cen1920: ["1920 census, Fayette Co., Pa., ED 93, sheet 19B: Amadee G. Clemmer, 39, wife Elizabeth, and children Irene V., William B. (11), Grace E. and Bruce S.", FS + "MFRT-JGS"],
  cen1930dun: ["1930 census, Georges Twp., Fayette Co., Pa.: Martin Dunham, 66, wife Emma, 49, daughter Margaret B., and eight other children", FS + "XHS1-TWF"],
  cen1940: ["1940 census, Springhill Twp. outside Point Marion, Fayette Co., Pa., ED 26-109, sheet 7A: William Clemmer, 32, wife Margaret, 24, son Thomas, 6; same house in 1935", FS + "KQQT-ZF2"],
  draft1940: ["WWII draft registration, Point Marion, 16 Oct 1940: William Bryon Clemmer, born 27 June 1908 in Fayette Co., employed by the WPA; contact Margaret Belle Clemmer", FS + "Q2SN-99XF"],
  cen1950: ["1950 census, Springhill Twp., Fayette Co., Pa., ED 26-200, p. 11: William Clemmer, 41, coal-mine operator, wife Bell, 34, children Phyllis, Jacqueline, Bernard and William Jr. (1), and Neil T. Dunham, 14", FS + "6XBG-KX7S"],
  cen1950jr: ["1950 census, Springhill Twp., Fayette Co., Pa.: William Clemmer Jr., 1, son of William and Bell Clemmer", FS + "6XBG-KX77"],
  marr1938: ["Monongalia Co., W.Va., marriage license, pp. 432–433: William Bryan Clemmer, 29, born Point Marion, son of Amadee Clemmer and Elizabeth Wilkins, and Margaret Belle Dunham, 21, born 22 Mar 1916 at Smithfield, Pa., daughter of Martin Dunham and Emma Miller; applied 29 Sep, married at Morgantown 14 Oct 1938 by Bernard Gibbs, M.E. minister", "https://archive.wvculture.org/vrr/va_mcdetail.aspx?Id=11349379"],
  ssdiWm: ["Social Security Death Index: William Clemmer, born 27 June 1908, died May 1982, last residence Point Marion", FS + "J2SJ-MP8"],
  fagWm: ["Find a Grave memorial 144874872: William Bryan Clemmer Sr., born 27 June 1908 at Springhill, died May 1982 at Point Marion, buried Evergreen Memorial Park, Point Marion; headstone “William Clemmer, Sr., 1908–1982”; links his half-son Thomas Neil Dunham (1935–2021)", "https://www.findagrave.com/memorial/144874872/william-bryan-clemmer"],
  fagNeil: ["Find a Grave memorial 226100459: Thomas Neil Dunham, 1935–2021", "https://www.findagrave.com/memorial/226100459/thomas_neil-dunham"],
  fagGrace: ["Find a Grave memorial 5661682: Grace Yvonne Clemmer Nigro, 1910–1979, linked as a daughter of Amadee and Elizabeth Clemmer", "https://www.findagrave.com/memorial/5661682/grace_yvonne-nigro"],
  fagIrene: ["Find a Grave memorial 63833732: Irene E. Clemmer DiPietro, 1912–1952, linked as a daughter of Amadee and Elizabeth Clemmer", "https://www.findagrave.com/memorial/63833732/irene_e-dipietro"],
  fagBruce: ["Find a Grave memorial 144874429: Bruce Sterling Clemmer, 1917–1987, linked as a son of Amadee and Elizabeth Clemmer", "https://www.findagrave.com/memorial/144874429/bruce_sterling-clemmer"],
  fagBernard: ["Find a Grave memorial 124675818: Bernard Dale “Bernie” Clemmer, 1946–2003, linked as a son of William Bryan Clemmer", "https://www.findagrave.com/memorial/124675818/bernard_dale-clemmer"],
  fagIona: ["Find a Grave memorial 108666903: Iona Alice Clemmer Molesy, 1868–1954", "https://www.findagrave.com/memorial/108666903/iona_alice-molesy"],
  dcJasper1840: ["Pennsylvania death certificate index (Ancestry): Jasper Clemmer, born 16 Jan 1840, died 6 July 1922 at Springhill Twp.; parents Andrew and Mariah", "https://www.ancestry.com/search/collections/5164/records/918300"],
  dcJasperE: ["Pennsylvania death certificate index (Ancestry): Jasper E. Clemmer, born 29 Nov 1862, died 26 Dec 1931 at Springhill Twp.; parents Lebby and Caroline; spouse Delia", "https://www.ancestry.com/search/collections/5164/records/4903016"],
  dcJoseph: ["Pennsylvania death certificate index (Ancestry): Joseph Clemmer, born 4 Sep 1872, died 8 Aug 1959 at Uniontown; father L. B. Clemmer, mother given as Stella Dunn", "https://www.ancestry.com/search/collections/5164/records/6239553"],
  dcHarvey: ["Pennsylvania death certificate index (Ancestry): Harvey Wilkins, born 12 Dec 1878, died 18 July 1937 at Uniontown; parents Henry H. and Mary Wilkins; spouse Cora", "https://www.ancestry.com/search/collections/5164/records/3109615"],
  pensionMichael: ["Civil War pension index card: Michael Clemmer, Co. K, 116th Pa. Infantry; father's pension claimed by Andrew Clemmer, filed May 1887 (application 354,265, certificate 243,706), from Pennsylvania", FS + "KD5Q-8CN"],
  regMichael: ["Pennsylvania register of military volunteers, p. 534, entry 23: Michael Clemmer, enlisted at Uniontown 31 Mar 1864 for three years, Co. K, 116th Regiment (age given as 28)", FS + "4LY7-72ZM"],
  fagMichael: ["Find a Grave index: Michael Clemmer, born 8 May 1842, died 3 June 1864, buried Cold Harbor National Cemetery, Mechanicsville, Va.", FS + "QVVN-9KDF"],
  estateMichael: ["Fayette Co. Orphans' Court, Estate of Michael Clemmer, dec'd, No. 16 June Court 1868, auditor's report (A. E. Willson), pp. 289–290: Michael died intestate, unmarried and without issue; William Parshall appeared for Andrew Clemmer, father of the decedent, and Daniel Kaine for Mrs. Delilah Crow, his sister and daughter-in-law of Hon. Alexander Crow, who claimed the bounty money Michael left with the judge on going into the army; the balance of $236.25 distributed to Andrew Clemmer, father", "https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSSH-KGYC"],
  nelsonK116: ["Nelson's Biographical Dictionary of Fayette County (1900), p. 198: roster of Co. K, 116th Pa. Infantry, a Fayette County company, including Michael Clemmer", "https://archive.org/details/nelsonsbiographi01shep"],
  dcFrank: ["Pennsylvania death certificate index (Ancestry): Frank P. Clemmer, born 16 Jan 1853, died 4 May 1934 at Springhill Twp.; parents Andrew and Mariah", "https://www.ancestry.com/search/collections/5164/records/3246694"],
  cen1860dunham: ["1860 census, Springhill Twp., Fayette Co., Pa., p. 225: Jno Dunham, 30, Rebecca, 26, and Jno, 1", FS + "MXPL-8YZ"],
  marr1889dunham: ["Fayette Co., Pa., marriage license, 2 Dec 1889, Uniontown: John Dunham, 29, son of John and Rebecca Dunham, and Lucinda Dukate, 18", FS + "VFSB-8CR"],
  cen1850dunham: ["1850 census, Springhill Twp., Fayette Co., Pa.: Martin Dunham, 47, born N.J., Elizabeth, 45, born Va., with Sarah (24), John (19, born Va.), Othe (13), Sarah (11), William (7) and Westley (7) Dunham; relationships not stated", FS + "M4HD-8DT"],
  fagElizabeth: ["Find a Grave memorial 39473359: Elizabeth Wilkins Clemmer, 1884–1931", "https://www.findagrave.com/memorial/39473359/elizabeth-clemmer"],
  cen1880: ["1880 census, Springhill Twp., Fayette Co., Pa., ED 56: Lebous Clemmer, 49, wife Caroline, 39, and children Jasper (17), Elle M. (14), Oney A. (10), Joseph (7), Oliver S. (3) and Amada (3 months)", FS + "MWF8-YP5"],
  dcLebbeus: ["Pennsylvania death certificate 15443 (1909): Libbens [Lebbeus] Bigelow Clemmer, born 15 Jan 1832 in Pennsylvania, died 23 Feb 1909 at Springhill Twp., aged 77, married, a brick molder, of chronic Bright's disease; father Andrew Clemmer (born Pa.), mother Moriah Halphin (born W.Va.); informant Frank Clemmer, Cheat Haven, Pa.; buried Mt. Moriah Cemetery 25 Feb 1909", "https://www.ancestry.com/search/collections/5164/records/2560967"],
  fagMargaret: ["Find a Grave index: Margaret Belle Dunham Clemmer, 21 Mar 1916 – 11 Apr 1979, Evergreen Memorial Park, Point Marion", FS + "QK15-38KB"],
  numident: ["Social Security application index (NUMIDENT): names William B. Clemmer and Margaret B. Dunham as a child's parents", FS + "6K9G-CK4S"],
  obitNeil: ["Obituary of T. Neil Dunham (1935–2021), Oakland, Md.: names his mother, Margaret Belle Dunham Clemmer, her husband William Clemmer, and his brothers and sisters Bernard, William, Phyllis and Jacqueline", FS + "XMWD-Z9XF"],
  dcAmadee: ["Pennsylvania death certificate 49787 (1921): Amadee H. Clemmer, born 13 Feb 1880, died 4 May 1921 at Springhill Twp., clerk in a grocery store, of laryngeal and pulmonary tuberculosis; father Lebius Clemmer, mother Caroline Rumble, both born Pa.; informant Mrs. Elizabeth Clemmer, R.F.D. 12 Point Marion; buried Mt. Moriah Cemetery 6 May 1921", "https://www.ancestry.com/search/collections/5164/records/624727"],
  cen1850: ["1850 census, Springhill Twp., Fayette Co., Pa., dwelling 235: Andrew Clemmen, 40, Maria, 38, and children Lebbens (18), Jacob (15), Delila (12), Gasper (9), Michael (7), Minerva (6), Margaret (5) and Barbary A. (2)", FS + "M4HD-KVZ"],
  cen1880andrew: ["1880 census, Springhill Twp., Fayette Co., Pa., ED 56: Andrew Clemmer, 69, laborer, living in the household of Nicholas Ganow", FS + "MWF8-PCM"],
  dcCaroline: ["Pennsylvania death certificate 114721 (1909): Caroline Clemmer, born 10 Jan 1841 in Pa., died 24 Dec 1909 at Springhill Twp., married, of mitral heart disease; father Godfrey Rumble, mother Rebecca Varner; informant Jasper Clemmer Sr., Cheat Haven; buried Mt. Moriah 26 Dec 1909", "https://www.ancestry.com/search/collections/5164/records/281182"],
  marr1907: ["Fayette Co., Pa., marriage license docket 44, p. 47, license 19339, 4 Sep 1907: Amedee Clemmer, 27, huckster, of Cheat Haven, born Fayette Co., son of Leebbius and Caroline Clemmer, and Eliza Wilkins, 24, of Smithfield, born Morgantown, W.Va., daughter of Harry and Mary", "https://www.ancestry.com/search/collections/61381/records/2789906"],
  cen1900wilkins: ["1900 census, Springhill Twp., Fayette Co., Pa.: Henry H. Wilkens, born Dec 1843 in W.Va., wife Mary C., born July 1844 in W.Va., and children including Maggie, Melenda, Harvey, Chas and Eliza E., born Sept 1884 in W.Va.", FS + "M3SG-DH9"],
  dcHenryW: ["Pennsylvania death certificate 81393 (1913): Henry H. Wilkins, born 12 Dec 1841 in W.Va., died 1 July 1913 at Springhill Twp., married, a laborer; father not named (born W.Va.), mother Lisa Blaney (born W.Va.); cause of death recorded as suicide; informant Harry Wilkins, Smithfield R.D. 6; buried Springhill Cemetery 2 July 1913", "https://www.ancestry.com/search/collections/5164/records/2347693"],
  dcMaryW: ["Pennsylvania death certificate 42451 (1927): Mary C. Wilkins, widow, born 1 July 1845 at Masontown, W.Va., died 17 Apr 1927 at Springhill Twp.; father given as Jack Wilkins and mother as Elizabeth, both of Masontown; informant her son Harvey Wilkins, Smithfield; buried Springhill Cemetery", "https://www.ancestry.com/search/collections/5164/records/4400094"],
  cen1850blaney: ["1850 census, Preston Co., Va., dwelling 81: John H. Blanz [Blaney], 29, Eliza, 34, Isaac I., 2, Joanna, infant, with Hannah Wilkins, 16, Henry H. Wilkins, 11, and Eliza I. Wilkins, 6", FS + "M8DK-4SD"],
  cen1860blaney: ["1860 census, District 5, Preston Co., Va., p. 220: John H. Blaney, 39, Eliza, 45, Isaac J., Joanna, Jonathan and Phebe E. Blaney, with William Wilkins, 22, Henry H. Wilkins, 18, and Eliza J. Wilkins, 16", FS + "M41T-FLH"],
  pensionHenryW: ["Civil War pension index card: Henry H. Wilkins, Co. C, 3rd W.Va. Infantry and Co. C, 6th W.Va. Cavalry; invalid pension applied 27 Aug 1889 (application 724,699, certificate 534,192) and widow Mary C. Wilkins's pension applied 10 July 1913 (application 1,011,862, certificate 777,604), both from Pennsylvania", FS + "QJD5-W5RH"],
  wileyPreston: ["Wiley, History of Preston County (1882), roster of Co. C, 3rd W.Va. Volunteer Infantry: Henry H. Wilkins; J. H. Blaney among the veterans", "https://archive.org/details/historyofpreston00wile"],
  dcMartin: ["Pennsylvania death certificate 72324 (1943): Martin Dunham, born 12 May 1863 in Fayette Co., died 26 Aug 1943 at Springhill Twp., residence rural Point Marion, a farmer, of a stroke; father John Dunham, mother Rebecca Dewalt, both born Fayette Co.; informant Joe Dunham, Fairchance", "https://www.ancestry.com/search/collections/5164/records/4646075"],
  dcEmma: ["Pennsylvania death certificate 26280 (1942): Mrs. Emma Dunham, born 7 Jan 1881 in Fayette Co., died 15 Mar 1942 at Georges Twp. (Smithfield R.D. 1) of diabetic coma, wife of Martin Dunham, 79; father Wm Miller, mother Ida Emme, both born Fayette Co.; informant Jo Dunham, Fairchance", "https://www.ancestry.com/search/collections/5164/records/3877890"],
  marr1899: ["Fayette Co., Pa., marriage license 9443, 24 Aug 1899, Uniontown: Martin Dunham, 36, son of John and Rebecca, and Emma Miller, 18, daughter of Wm. G. and Ida", FS + "VF32-6MY"],
  cen1880martin: ["1880 census, Springhill Twp., Fayette Co., Pa.: Martin Dunham, 17, living and working in the household of Franklin Stewart", FS + "MWF8-YJR"],
  fagMartin: ["Find a Grave index: Martin Dunham, 12 May 1863 – 26 Aug 1943, Miller-Sisler Cemetery, Haydentown, Georges Twp.", FS + "QV2R-1GJ4"],
  fagAmadee: ["Find a Grave memorial 39473331: Amadee Clemmer, born 13 Feb 1880 at Springhill, died 11 Apr 1921, buried Mount Moriah Presbyterian Cemetery, Point Marion; married Elizabeth Wilkins 1907. It links Iona Alice Clemmer Molesy (1868–1954) as his mother; the 1880 census shows her as his sister", "https://www.findagrave.com/memorial/39473331/amadee-clemmer"],
};

// ---------- People ----------
// { id, name, short?, b, d, gen, line, lineLabel?, direct?, probable?, place, role?,
//   lede, facts:{…}, sources:[S.key, …] }
// Living people: name and links only — no dates, places or map stops.
const P = [
  { id:"april", name:"April Millet", short:"April Millet", gen:0, line:"clem", direct:true,
    lede:"Born April Clemmer, daughter of Bill Clemmer.",
    sources:[S.family] },
  { id:"billjr", name:"William “Bill” Clemmer", short:"Bill Clemmer", gen:1, line:"clem", direct:true,
    lede:"William Clemmer Jr., the son of William Bryan Clemmer and Margaret Belle Dunham.",
    sources:[S.family, S.cen1950jr] },
  { id:"neildunham", name:"Thomas Neil Dunham", short:"Neil Dunham", b:"1935", d:"2021", gen:1, line:"dun", lineLabel:"Dunham line",
    place:"Fayette Co., Pa. → Mountain Lake Park, Md.",
    lede:"Margaret Belle Dunham's son, born in Fayette County on 12 April 1935, three years before her marriage to William Bryan Clemmer. He grew up in their house in Springhill Township: the 1940 census counts him as Thomas Clemmer, 6, and the 1950 census as Neil T. Dunham, 14, alongside his half-sisters and half-brothers. He died at Mountain Lake Park, Maryland, on 23 April 2021, aged 86; his obituary names his mother and his brothers and sisters Bernard, William, Phyllis and Jacqueline.",
    facts:{ Born:"12 Apr 1935, Fayette Co., Pa.", Died:"23 Apr 2021, Mountain Lake Park, Md." },
    sources:[S.cen1940, S.cen1950, S.obitNeil, S.fagWm, S.fagNeil] },
  { id:"wbclemmer", name:"William Bryan Clemmer", short:"William B. Clemmer", b:"1908", d:"1982", gen:2, line:"clem", direct:true,
    place:"Point Marion → Springhill Twp., Fayette Co., Pa.", role:"Coal-mine operator",
    lede:"Born at Point Marion on 27 June 1908, William was twelve when his father died of tuberculosis in 1921. He married Margaret Belle Dunham at Morgantown, across the state line, on 14 October 1938; he was 29 and she 21. In 1940 he was working for the WPA and living just outside Point Marion; by 1950 he was running a coal mine in Springhill Township, with five children in the house. He died in May 1982 and is buried beside Margaret in Evergreen Memorial Park at Point Marion, under a flat stone that reads William Clemmer, Sr.",
    facts:{ Born:"27 June 1908; Point Marion by his marriage license, Springhill by his memorial", Married:"14 Oct 1938, Morgantown, W.Va.", Died:"May 1982 (Social Security Death Index)", Burial:"Evergreen Memorial Park, Point Marion", Household:"The son Thomas, 6, in the 1940 census is Margaret's son Thomas Neil Dunham (1935–2021), counted under the Clemmer name; he is Neil T. Dunham in 1950, and William's memorial links him as a son." },
    sources:[S.cen1910, S.cen1920, S.marr1938, S.cen1940, S.draft1940, S.cen1950, S.ssdiWm, S.fagWm, S.numident] },
  { id:"mbdunham", name:"Margaret Belle Dunham", short:"Margaret Belle Dunham", b:"1916", d:"1979", gen:2, line:"dun", direct:true,
    place:"Smithfield → Springhill Twp., Fayette Co., Pa.",
    lede:"Born at Smithfield on 22 March 1916 by her marriage license (21 March by the grave index), Margaret was the daughter of Martin Dunham and Emma Miller and was fourteen and living with them in Georges Township in 1930. She married William Bryan Clemmer in 1938 and was counted as Bell in the 1950 census. She died on 11 April 1979 and is buried in Evergreen Memorial Park at Point Marion.",
    facts:{ Born:"22 Mar 1916, Smithfield, Pa. (marriage license)", Died:"11 Apr 1979", Burial:"Evergreen Memorial Park, Point Marion" },
    sources:[S.cen1930dun, S.marr1938, S.draft1940, S.cen1940, S.cen1950, S.fagMargaret, S.numident, S.obitNeil] },
  { id:"amadee", name:"Amadee H. Clemmer", short:"Amadee Clemmer", b:"1880", d:"1921", gen:3, line:"clem", direct:true,
    place:"Springhill Twp., Fayette Co., Pa.", role:"Grocery clerk",
    lede:"Born on 13 February 1880, Amadee appears as A. H. Clemmer in 1910 and Amadee G. in 1920, in Springhill Township with his wife Elizabeth and their children. He clerked in a grocery store and died at home on 4 May 1921, aged 41, of laryngeal and pulmonary tuberculosis he had carried for most of a year. He was buried in the Mount Moriah Presbyterian Cemetery at Point Marion two days later. His death certificate names his parents as Lebius Clemmer and Caroline Rumble, and the 1880 census shows him at three months old in their house in Springhill, the youngest of six.",
    facts:{ Born:"13 Feb 1880, Pennsylvania", Died:"4 May 1921, Springhill Twp. (the grave index says 11 April; the certificate is the record)", Children:"Irene V., William B., Grace E., Bruce S. (1920 census)", Name:"His middle initial is H. on his death certificate and G. in the 1920 census.", Married:"Eliza Wilkins, 4 Sep 1907, Fayette Co. license 19339; he was a huckster living at Cheat Haven", Siblings:"Jasper, Elle M., Oney A. (Iona Alice), Joseph, Oliver S. (1880 census)" },
    sources:[S.cen1880, S.marr1907, S.cen1910, S.cen1920, S.dcAmadee, S.fagAmadee, S.marr1938] },
  { id:"elizwilkins", name:"Elizabeth Wilkins", short:"Elizabeth Wilkins", b:"1884", d:"1931", gen:3, line:"clem", lineLabel:"Wilkins line", direct:true,
    place:"Morgantown, W.Va. → Springhill Twp., Fayette Co., Pa.",
    lede:"Born at Morgantown, West Virginia, in September 1884 (the 7th, by her grave), Eliza was sixteen and living with her parents, Henry and Mary Wilkins, in Springhill Township in 1900. She married Amadee Clemmer on 4 September 1907; her license names her parents as Harry and Mary. She was Eliza in 1910 and Elizabeth in 1920, and was widowed in 1921, when she gave the details for Amadee's death certificate from R.F.D. 12, Point Marion. She died on 2 April 1931.",
    facts:{ Born:"7 Sep 1884, Morgantown, W.Va.", Married:"4 Sep 1907, Fayette Co.", Died:"2 Apr 1931 (Find a Grave)", "Not found":"Her death certificate: not in the Pennsylvania index under any name for that date and county, nor in the West Virginia death index." },
    sources:[S.cen1900wilkins, S.marr1907, S.cen1910, S.cen1920, S.dcAmadee, S.marr1938, S.fagElizabeth] },
  { id:"henrywilkins", name:"Henry H. Wilkins", short:"Henry Wilkins", b:"1841", d:"1913", gen:4, line:"clem", lineLabel:"Wilkins line", direct:true,
    place:"Preston Co., W.Va. → Springhill Twp., Fayette Co., Pa.", role:"Union soldier",
    lede:"Born in (West) Virginia on 12 December 1841, Henry grew up in Preston County in the household of his mother, Eliza, and her second husband, John H. Blaney: he was 11 there in 1850 and 18 in 1860. He served in the Civil War in Company C of the 3rd West Virginia Infantry, which became the 6th West Virginia Cavalry, alongside his stepfather, and drew an invalid pension from 1889. He and Mary moved between Preston County and Springhill Township, Pennsylvania, where they were living by 1900. He died there on 1 July 1913, by his own hand, and is buried in the Springhill Cemetery. His daughter Eliza's marriage license calls him Harry.",
    facts:{ Born:"12 Dec 1841, West Virginia", Died:"1 July 1913, Springhill Twp.", Service:"Co. C, 3rd W.Va. Inf.; Co. C, 6th W.Va. Cav.", Siblings:"Hannah, William, Eliza J. (1850 and 1860 censuses)", "Open question":"His father, a Wilkins who died or left before about 1847, is not yet named in any record." },
    sources:[S.cen1850blaney, S.cen1860blaney, S.wileyPreston, S.pensionHenryW, S.cen1900wilkins, S.marr1907, S.dcHenryW] },
  { id:"elizablaney", name:"Eliza (Wilkins) Blaney", short:"Eliza Blaney", b:"c. 1815", gen:5, line:"clem", lineLabel:"Wilkins line", direct:true,
    place:"Preston Co., (West) Virginia",
    lede:"Henry's mother, named Lisa Blaney on his death certificate. The censuses show why: in 1850 and 1860 she is Eliza, wife of John H. Blaney, in Preston County, with her Wilkins children Hannah, William, Henry and Eliza living with the young Blaneys. So Blaney is her second married name, and her first husband, Henry's father, was a Wilkins. Her maiden name is not yet known.",
    facts:{ Born:"About 1815, Virginia (34 in 1850, 45 in 1860)", Married:"(1) ___ Wilkins; (2) John H. Blaney, by about 1847" },
    sources:[S.dcHenryW, S.cen1850blaney, S.cen1860blaney] },
  { id:"marycwilkins", name:"Mary C. Wilkins", short:"Mary C. Wilkins", b:"1845", d:"1927", gen:4, line:"clem", lineLabel:"Wilkins line", direct:true,
    place:"Masontown, W.Va. → Springhill Twp., Fayette Co., Pa.",
    lede:"Born at Masontown in Preston County on 1 July 1845 (July 1844 by the 1900 census), Mary C. was Henry's wife and is named as Eliza's mother on her marriage license. Widowed in 1913, she took up his pension and died in Springhill Township on 17 April 1927. Her death certificate gives her parents as Jack Wilkins and Elizabeth, both of Masontown; the informant was her son, and Wilkins may be her married name set down in error. Her maiden name is the open question here.",
    facts:{ Born:"1 July 1845, Masontown, W.Va.", Died:"17 Apr 1927, Springhill Twp.", "Open question":"Maiden name. Her widow's pension file (certificate 777,604) should give the marriage." },
    sources:[S.cen1900wilkins, S.marr1907, S.pensionHenryW, S.dcMaryW] },
  { id:"martindunham", name:"Martin Dunham", short:"Martin Dunham", b:"1863", d:"1943", gen:3, line:"dun", direct:true,
    place:"Springhill Twp. → Georges Twp., Fayette Co., Pa.", role:"Farmer",
    lede:"Born in Fayette County on 12 May 1863, the son of John Dunham and Rebecca Dewalt, Martin was seventeen in 1880 and working in Franklin Stewart's household in Springhill Township. He married Emma Miller at Uniontown on 24 August 1899, when he was 36 and she 18. In 1930 he was farming in Georges Township with Emma and nine children, from Paul, 21, to Pearl, 7. Emma died in 1942; Martin died the next year, on 26 August 1943, near Point Marion, and is buried in the Miller-Sisler Cemetery at Haydentown.",
    facts:{ Born:"12 May 1863, Fayette Co.", Married:"24 Aug 1899, Uniontown", Died:"26 Aug 1943, Springhill Twp.", Children:"Paul, Herbert, Clarence, Harry S., Eleanore C., Margaret B., Franklin W., Edith, Pearl (1930 census); Joe, the informant on both parents' certificates" },
    sources:[S.cen1880martin, S.marr1899, S.cen1930dun, S.dcMartin, S.fagMartin, S.marr1938] },
  { id:"emmamiller", name:"Emma Miller", short:"Emma Miller", b:"1881", d:"1942", gen:3, line:"dun", lineLabel:"Miller line", direct:true,
    place:"Georges Twp., Fayette Co., Pa.",
    lede:"Born in Fayette County on 7 January 1881, the daughter of William G. Miller and Ida, Emma married Martin Dunham at eighteen in 1899 and spent her life in Georges Township, where she was 49 with nine children at home in 1930. She died there, at Smithfield R.D. 1, of a diabetic coma on 15 March 1942.",
    facts:{ Born:"7 Jan 1881, Fayette Co.", Married:"24 Aug 1899, Uniontown", Died:"15 Mar 1942, Georges Twp." },
    sources:[S.marr1899, S.cen1930dun, S.dcEmma, S.marr1938] },
  { id:"johndunham", name:"John Dunham", short:"John Dunham", b:"c. 1830", gen:4, line:"dun", direct:true,
    place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Named as Martin's father on his 1899 marriage license and his 1943 death certificate. In 1860 a John Dunham, 30, was living in Springhill Township with his wife Rebecca, 26, and a son John, a year old, who as John Dunham, 29, “son of John and Rebecca”, married at Uniontown in 1889; Martin was born three years after that census. In 1850 a John Dunham, 19, born in Virginia, was living in Springhill in the household of Martin Dunham, born in New Jersey, and his wife Elizabeth, probably his parents. The birthplaces disagree: Virginia in 1850, Pennsylvania in 1860, Fayette County on Martin's certificate.",
    facts:{ Born:"About 1830 (30 in 1860; 19 in 1850)" },
    sources:[S.cen1850dunham, S.cen1860dunham, S.marr1889dunham, S.marr1899, S.dcMartin] },
  { id:"rebeccadewalt", name:"Rebecca Dewalt", short:"Rebecca Dewalt", b:"c. 1834", gen:4, line:"dun", lineLabel:"Dewalt line", direct:true,
    place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Named as Martin's mother on his 1899 marriage license (as Rebecca) and his 1943 death certificate (as Rebecca Dewalt, born in Fayette County). She is Rebecca, 26, wife of John Dunham, in the 1860 census of Springhill Township. Other researchers spell her maiden name DeVault and give her death as 1899; not yet seen in a record here.",
    sources:[S.cen1860dunham, S.marr1889dunham, S.marr1899, S.dcMartin] },
  { id:"johndunhamjr", name:"John Dunham", short:"John Dunham Jr.", b:"c. 1859", gen:3, line:"dun", probable:true,
    place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of John and Rebecca Dunham, a year old in their Springhill household in 1860, and 29 when he married Lucinda Dukate at Uniontown in 1889, his license naming his parents as John and Rebecca. Carried as Martin's brother on the strength of the same parents' names in the same township; no record yet names them together.",
    sources:[S.cen1860dunham, S.marr1889dunham] },
  { id:"martindunhamsr", name:"Martin Dunham", short:"Martin Dunham (b. c. 1803)", b:"c. 1803", gen:5, line:"dun", direct:true, probable:true,
    place:"New Jersey → Springhill Twp., Fayette Co., Pa.",
    lede:"Born in New Jersey about 1803, living in Springhill Township in 1850 with his wife Elizabeth and a household of Dunhams that included John, 19. The census does not state relationships, so he is carried as John's probable father; his grandson's name, Martin, points the same way.",
    sources:[S.cen1850dunham] },
  { id:"elizabethdunham", name:"Elizabeth Dunham", short:"Elizabeth Dunham", b:"c. 1805", gen:5, line:"dun", direct:true, probable:true,
    place:"Virginia → Springhill Twp., Fayette Co., Pa.",
    lede:"Born in Virginia about 1805, wife of Martin Dunham in the 1850 census of Springhill Township; John Dunham's probable mother. Her maiden name is not known.",
    sources:[S.cen1850dunham] },
  { id:"wmgmiller", name:"William G. Miller", short:"William G. Miller", gen:4, line:"dun", lineLabel:"Miller line", direct:true,
    place:"Fayette Co., Pa.",
    lede:"Named as Emma's father on her 1899 marriage license (Wm. G.) and her 1942 death certificate (Wm Miller, born in Fayette County).",
    sources:[S.marr1899, S.dcEmma] },
  { id:"idaemme", name:"Ida Emme", short:"Ida Emme", gen:4, line:"dun", lineLabel:"Miller line", direct:true,
    place:"Fayette Co., Pa.",
    lede:"Named as Emma's mother on her 1899 marriage license (Ida) and her 1942 death certificate, which gives her maiden name as Emme, born in Fayette County. The surname is as the certificate spells it; the index read it as Ian Emme.",
    sources:[S.marr1899, S.dcEmma] },
  { id:"lebius", name:"Lebbeus Bigelow Clemmer", short:"Lebbeus B. Clemmer", b:"1832", d:"1909", gen:4, line:"clem", direct:true,
    place:"Springhill Twp., Fayette Co., Pa.", role:"Brick molder",
    lede:"Born on 15 January 1832, the son of Andrew Clemmer and Moriah Halphin, Lebbeus is Lebous in the 1880 census and Lebius on his son Amadee's death certificate. In 1880 he was 49 and living in Springhill Township with his wife Caroline and six children, the youngest, Amadee, three months old. A brick molder, he died there of chronic Bright's disease on 23 February 1909, aged 77, and was buried at Mt. Moriah Cemetery. His son Frank, of Cheat Haven, gave the details.",
    facts:{ Born:"15 Jan 1832, Pennsylvania", Died:"23 Feb 1909, Springhill Twp.", Children:"Jasper, Elle M., Oney A. (Iona Alice), Joseph, Oliver S., Amadee (1880 census); Frank (informant, 1909)" },
    sources:[S.cen1850, S.cen1880, S.marr1907, S.dcLebbeus, S.dcAmadee] },
  { id:"carolinerumble", name:"Caroline Rumble", short:"Caroline Rumble", b:"1841", d:"1909", gen:4, line:"clem", lineLabel:"Rumble line", direct:true,
    place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Born in Pennsylvania on 10 January 1841, the daughter of Godfrey Rumble and Rebecca Varner, Caroline was 39 in 1880, keeping house in Springhill Township for Lebbeus and six children. She outlived him by ten months and died of heart disease on Christmas Eve 1909. Her son Jasper Clemmer Sr. of Cheat Haven gave the details, and she was buried at Mt. Moriah two days later.",
    facts:{ Born:"10 Jan 1841, Pennsylvania", Died:"24 Dec 1909, Springhill Twp." },
    sources:[S.cen1880, S.marr1907, S.dcCaroline, S.dcAmadee, S.dcLebbeus] },
  { id:"godfreyrumble", name:"Godfrey Rumble", short:"Godfrey Rumble", gen:5, line:"clem", lineLabel:"Rumble line", direct:true,
    place:"Pennsylvania",
    lede:"Named as Caroline's father on her 1909 death certificate.",
    sources:[S.dcCaroline] },
  { id:"rebeccavarner", name:"Rebecca Varner", short:"Rebecca Varner", gen:5, line:"clem", lineLabel:"Varner line", direct:true,
    place:"Pennsylvania",
    lede:"Named as Caroline's mother on her 1909 death certificate.",
    sources:[S.dcCaroline] },
  { id:"andrewclemmer", name:"Andrew Clemmer", short:"Andrew Clemmer", b:"c. 1810", gen:5, line:"clem", direct:true,
    place:"Springhill Twp., Fayette Co., Pa.", role:"Laborer",
    lede:"Born in Pennsylvania about 1810, Andrew was 40 in 1850 and living in Springhill Township with his wife Maria and nine children, from Lebbeus, 18, to Barbary A., 2. In 1868–69 he claimed his son Michael's estate in the Orphans' Court and received it over the claim of his daughter Delilah; in 1880 he was 69, still in Springhill, working as a laborer and living in Nicholas Ganow's household; and in 1887 he applied for a father's pension for Michael. Where he came from is the next question: Clemmers were heads of household in Springhill in 1820 (John, Lewis) and 1830 (Gasper, Jacob, Lewis), and a Jasper Clemmer was a school director there in 1846. Other researchers call him Andrew Blosser Clemmer, 1810–1887; no record here says so yet.",
    facts:{ Children:"Lebbeus, Jacob, Delila, Jasper, Michael, Minerva, Margaret, Barbary A. (1850 census)" },
    sources:[S.cen1850, S.estateMichael, S.cen1880andrew, S.pensionMichael, S.dcLebbeus] },
  { id:"moriahhalphin", name:"Moriah Halphin", short:"Moriah Halphin", gen:5, line:"clem", lineLabel:"Halphin line", direct:true,
    place:"West Virginia",
    b:"c. 1812",
    lede:"Named as Lebbeus's mother on his 1909 death certificate, born in (what became) West Virginia. She is Maria, 38, in the 1850 census, which gives her birthplace as Pennsylvania. The spelling is the certificate's; Mariah and Halpin or Halfin are likely variants to search.",
    sources:[S.cen1850, S.dcLebbeus] },
  { id:"phyllisclemmer", name:"Phyllis Clemmer Jacobs", short:"Phyllis Clemmer", gen:1, line:"clem",
    lede:"Daughter of William Bryan Clemmer and Margaret Belle Dunham; Phyllis Jacobs in her half-brother Neil's obituary.",
    sources:[S.cen1950, S.obitNeil] },
  { id:"jacquelineclemmer", name:"Jacqueline Clemmer Rosnick", short:"Jacqueline Clemmer", gen:1, line:"clem",
    lede:"Daughter of William Bryan Clemmer and Margaret Belle Dunham; Jacqueline Rosnick in her half-brother Neil's obituary.",
    sources:[S.cen1950, S.obitNeil] },
  { id:"bernardclemmer", name:"Bernard Dale Clemmer", short:"Bernard Clemmer", b:"1946", d:"2003", gen:1, line:"clem",
    lede:"Bernard Dale “Bernie” Clemmer, son of William Bryan Clemmer and Margaret Belle Dunham, was three in the 1950 census. He died in 2003.",
    sources:[S.cen1950, S.obitNeil, S.numident, S.fagBernard] },
  { id:"graceclemmer", name:"Grace Yvonne Clemmer Nigro", short:"Grace Clemmer", b:"1910", d:"1979", gen:2, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Amadee Clemmer and Elizabeth Wilkins, in their house in Springhill Township in 1910 and 1920 (Grace E. in 1920). She married a Nigro.",
    sources:[S.cen1920, S.fagGrace] },
  { id:"ireneclemmer", name:"Irene E. Clemmer DiPietro", short:"Irene Clemmer", b:"1912", d:"1952", gen:2, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Amadee Clemmer and Elizabeth Wilkins, Irene V. in the 1920 census; she married a DiPietro and died in 1952.",
    sources:[S.cen1920, S.fagIrene] },
  { id:"bruceclemmer", name:"Bruce Sterling Clemmer", short:"Bruce Clemmer", b:"1917", d:"1987", gen:2, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Amadee Clemmer and Elizabeth Wilkins, Bruce S. in the 1920 census. He was four when his father died.",
    sources:[S.cen1920, S.fagBruce] },
  { id:"pauldunham", name:"Paul Dunham", short:"Paul Dunham", b:"c. 1909", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Son of Martin Dunham and Emma Miller, 21 in the 1930 census.",
    sources:[S.cen1930dun] },
  { id:"herbertdunham", name:"Herbert Dunham", short:"Herbert Dunham", b:"c. 1911", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Son of Martin Dunham and Emma Miller, 19 in the 1930 census.",
    sources:[S.cen1930dun] },
  { id:"clarencedunham", name:"Clarence Dunham", short:"Clarence Dunham", b:"c. 1913", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Son of Martin Dunham and Emma Miller, 17 in the 1930 census.",
    sources:[S.cen1930dun] },
  { id:"eleanoredunham", name:"Eleanore C. Dunham", short:"Eleanore Dunham", b:"c. 1915", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Daughter of Martin Dunham and Emma Miller, 15 in the 1930 census.",
    sources:[S.cen1930dun] },
  { id:"harrydunham", name:"Harry S. Dunham", short:"Harry Dunham", b:"c. 1917", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Son of Martin Dunham and Emma Miller, 13 in the 1930 census.",
    sources:[S.cen1930dun] },
  { id:"franklindunham", name:"Franklin W. Dunham", short:"Franklin Dunham", b:"c. 1920", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Son of Martin Dunham and Emma Miller, 10 in the 1930 census.",
    sources:[S.cen1930dun] },
  { id:"edithdunham", name:"Edith Dunham", short:"Edith Dunham", b:"c. 1921", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Daughter of Martin Dunham and Emma Miller, 9 in the 1930 census.",
    sources:[S.cen1930dun] },
  { id:"pearldunham", name:"Pearl Dunham", short:"Pearl Dunham", b:"c. 1923", gen:2, line:"dun", place:"Georges Twp., Fayette Co., Pa.",
    lede:"Daughter of Martin Dunham and Emma Miller, 7 in the 1930 census, the youngest.",
    sources:[S.cen1930dun] },
  { id:"jasperEclemmer", name:"Jasper E. Clemmer", short:"Jasper E. Clemmer", b:"1862", d:"1931", gen:3, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"The eldest son of Lebbeus and Caroline, 17 in 1880. As Jasper Clemmer Sr. of Cheat Haven he gave the details for his mother's death certificate in 1909. He married Delia and died in Springhill Township in 1931.",
    sources:[S.cen1880, S.dcJasperE, S.dcCaroline] },
  { id:"elleclemmer", name:"Elle M. Clemmer", short:"Elle M. Clemmer", b:"c. 1866", gen:3, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Lebbeus and Caroline, 14 in the 1880 census.",
    sources:[S.cen1880] },
  { id:"ionaclemmer", name:"Iona Alice Clemmer Molesy", short:"Iona Clemmer", b:"1868", d:"1954", gen:3, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Lebbeus and Caroline, Oney A., 10, in the 1880 census. She married a Molesy. Find a Grave links her as Amadee's mother, which the 1880 census shows is wrong: she was his sister.",
    sources:[S.cen1880, S.fagIona] },
  { id:"josephclemmer", name:"Joseph Clemmer", short:"Joseph Clemmer", b:"1872", d:"1959", gen:3, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Lebbeus and Caroline, 7 in the 1880 census. His death certificate names his father as L. B. Clemmer; the mother it gives, Stella Dunn, is probably the informant's error or a stepmother's name, since the 1880 census puts him in Caroline's house.",
    sources:[S.cen1880, S.dcJoseph] },
  { id:"oliverclemmer", name:"Oliver S. Clemmer", short:"Oliver Clemmer", b:"c. 1877", gen:3, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Lebbeus and Caroline, 3 in the 1880 census.",
    sources:[S.cen1880] },
  { id:"minervawilkins", name:"Minerva Wilkins Swearingen", short:"Minerva Wilkins", b:"c. 1874", gen:3, line:"clem", lineLabel:"Wilkins line", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Henry and Mary Wilkins, living with them in 1900 as Minerva Swearingen, 26, born in Pennsylvania.",
    sources:[S.cen1900wilkins] },
  { id:"melendawilkins", name:"Melenda Wilkins", short:"Melenda Wilkins", b:"1876", gen:3, line:"clem", lineLabel:"Wilkins line", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Henry and Mary Wilkins, born September 1876 in West Virginia, 24 in the 1900 census.",
    sources:[S.cen1900wilkins] },
  { id:"harveywilkins", name:"Harvey Wilkins", short:"Harvey Wilkins", b:"1878", d:"1937", gen:3, line:"clem", lineLabel:"Wilkins line", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Henry and Mary Wilkins, born 12 December 1878 in West Virginia. He gave the details for his mother's death certificate in 1927, married Cora, and died at Uniontown in 1937.",
    sources:[S.cen1900wilkins, S.dcHarvey, S.dcMaryW] },
  { id:"maggiewilkins", name:"Maggie Wilkins", short:"Maggie Wilkins", b:"1881", gen:3, line:"clem", lineLabel:"Wilkins line", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Henry and Mary Wilkins, born January 1881 in Pennsylvania, 19 in the 1900 census.",
    sources:[S.cen1900wilkins] },
  { id:"chaswilkins", name:"Chas Wilkins", short:"Chas Wilkins", b:"1891", gen:3, line:"clem", lineLabel:"Wilkins line", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Henry and Mary Wilkins, born June 1891 in Pennsylvania, 9 in the 1900 census.",
    sources:[S.cen1900wilkins] },
  { id:"jacobclemmer", name:"Jacob Clemmer", short:"Jacob Clemmer", b:"c. 1835", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Andrew and Maria Clemmer, 15 in the 1850 census.",
    sources:[S.cen1850] },
  { id:"delilaclemmer", name:"Delilah Clemmer Crow", short:"Delilah Clemmer", b:"c. 1838", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Andrew and Maria Clemmer, 12 in the 1850 census. She married a son of Judge Alexander Crow. Her brother Michael left his army bounty money with the judge for her in 1864; in 1869 the Orphans' Court ruled that it had to go to their father instead.",
    sources:[S.cen1850, S.estateMichael] },
  { id:"jasperclemmer1840", name:"Jasper Clemmer", short:"Jasper Clemmer", b:"1840", d:"1922", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Andrew and Maria Clemmer, “Gasper”, 9, in the 1850 census. His death certificate names his parents as Andrew and Mariah; he died in Springhill Township in 1922.",
    sources:[S.cen1850, S.dcJasper1840] },
  { id:"michaelclemmer", name:"Michael Clemmer", short:"Michael Clemmer", b:"1842", d:"1864", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa. → Cold Harbor, Va.", role:"Union soldier",
    lede:"Son of Andrew and Maria Clemmer, 7 in the 1850 census. He enlisted at Uniontown on 31 March 1864 in Company K of the 116th Pennsylvania, a Fayette County company, and was killed at Cold Harbor on 3 June 1864, aged 22; he is buried in the national cemetery there. Before he left he gave his bounty money to Judge Alexander Crow to keep, to go to his sister Delilah if he did not come back. In 1869 the Orphans' Court found it had to go to his father instead, though, as the auditor wrote, Michael had wanted very strongly that she should have it and, for good reasons, that his father should not. Andrew later drew a father's pension for him.",
    facts:{ Born:"8 May 1842 (grave); 7 in 1850; the enlistment register's 28 is an error", Service:"Co. K, 116th Pa. Infantry, from 31 Mar 1864", Died:"3 June 1864, Cold Harbor, Va." },
    sources:[S.cen1850, S.regMichael, S.nelsonK116, S.fagMichael, S.estateMichael, S.pensionMichael] },
  { id:"minervaclemmer", name:"Minerva Clemmer", short:"Minerva Clemmer", b:"c. 1844", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Andrew and Maria Clemmer, 6 in the 1850 census.",
    sources:[S.cen1850] },
  { id:"margaretclemmer", name:"Margaret Clemmer", short:"Margaret Clemmer", b:"c. 1845", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Andrew and Maria Clemmer, 5 in the 1850 census.",
    sources:[S.cen1850] },
  { id:"frankclemmer", name:"Frank P. Clemmer", short:"Frank Clemmer", b:"1853", d:"1934", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Son of Andrew and Mariah Clemmer, born 16 January 1853, after the 1850 census. He died in Springhill Township in 1934. He is very probably the Frank Clemmer of Cheat Haven who gave the details for his brother Lebbeus's death certificate in 1909.",
    sources:[S.dcFrank, S.dcLebbeus] },
  { id:"barbaryclemmer", name:"Barbary A. Clemmer", short:"Barbary Clemmer", b:"c. 1848", gen:4, line:"clem", place:"Springhill Twp., Fayette Co., Pa.",
    lede:"Daughter of Andrew and Maria Clemmer, 2 in the 1850 census.",
    sources:[S.cen1850] },
  { id:"hannahwilkins", name:"Hannah Wilkins", short:"Hannah Wilkins", b:"c. 1834", gen:4, line:"clem", lineLabel:"Wilkins line", place:"Preston Co., (West) Virginia",
    lede:"Eliza's daughter, 16 in her mother's and stepfather's house in 1850.",
    sources:[S.cen1850blaney, S.cen1860blaney] },
  { id:"williamwilkins", name:"William Wilkins", short:"William Wilkins", b:"c. 1838", gen:4, line:"clem", lineLabel:"Wilkins line", place:"Preston Co., (West) Virginia",
    lede:"Eliza's son, 22 in the Blaney household in 1860.",
    sources:[S.cen1850blaney, S.cen1860blaney] },
  { id:"elizajwilkins", name:"Eliza J. Wilkins", short:"Eliza J. Wilkins", b:"c. 1844", gen:4, line:"clem", lineLabel:"Wilkins line", place:"Preston Co., (West) Virginia",
    lede:"Eliza's daughter, 6 in 1850 and 16 in 1860.",
    sources:[S.cen1850blaney, S.cen1860blaney] },
  { id:"johnhblaney", name:"John H. Blaney", short:"John H. Blaney", b:"c. 1821", gen:5, line:"other", lineLabel:"By marriage (Blaney)", place:"Preston Co., (West) Virginia",
    lede:"Eliza's second husband and Henry Wilkins's stepfather, 29 in 1850 and 39 in 1860, in Preston County. A J. H. Blaney served with Henry in Company C, 3rd West Virginia Infantry. Morton's history of Preston County has a Jonathan Blaney settling north of Masontown about 1818, whose grandson Isaac J. still lived there in 1914.",
    sources:[S.cen1850blaney, S.cen1860blaney, S.wileyPreston] },
  { id:"isaacblaney", name:"Isaac J. Blaney", short:"Isaac J. Blaney", b:"c. 1847", gen:4, line:"other", lineLabel:"Blaney half-siblings", place:"Preston Co., (West) Virginia",
    lede:"Son of John H. and Eliza Blaney, Henry Wilkins's half-brother; 2 in 1850 and 14 in 1860.",
    sources:[S.cen1850blaney, S.cen1860blaney] },
  { id:"joannablaney", name:"Joanna Blaney", short:"Joanna Blaney", b:"c. 1850", gen:4, line:"other", lineLabel:"Blaney half-siblings", place:"Preston Co., (West) Virginia",
    lede:"Daughter of John H. and Eliza Blaney, an infant in 1850 and 9 in 1860.",
    sources:[S.cen1850blaney, S.cen1860blaney] },
  { id:"jonathanblaney", name:"Jonathan Blaney", short:"Jonathan Blaney", b:"c. 1853", gen:4, line:"other", lineLabel:"Blaney half-siblings", place:"Preston Co., (West) Virginia",
    lede:"Son of John H. and Eliza Blaney, 7 in the 1860 census.",
    sources:[S.cen1850blaney, S.cen1860blaney] },
  { id:"phebeblaney", name:"Phebe E. Blaney", short:"Phebe E. Blaney", b:"c. 1856", gen:4, line:"other", lineLabel:"Blaney half-siblings", place:"Preston Co., (West) Virginia",
    lede:"Daughter of John H. and Eliza Blaney, 4 in the 1860 census.",
    sources:[S.cen1850blaney, S.cen1860blaney] },
];

// ---------- Relationships ----------
// [from, to, type, probable?]; types: parent (parent → child), spouse, sibling,
// grand (a generation is missing between)
const E = [
  ["billjr","april","parent"],
  ["wbclemmer","mbdunham","spouse"],
  ["wbclemmer","billjr","parent"], ["mbdunham","billjr","parent"],
  ["mbdunham","neildunham","parent"],
  ["neildunham","billjr","sibling"],
  ["amadee","elizwilkins","spouse"],
  ["amadee","wbclemmer","parent"], ["elizwilkins","wbclemmer","parent"],
  ["martindunham","emmamiller","spouse"],
  ["martindunham","mbdunham","parent"], ["emmamiller","mbdunham","parent"],
  ["lebius","carolinerumble","spouse"],
  ["andrewclemmer","frankclemmer","parent"], ["moriahhalphin","frankclemmer","parent"],
  ["lebius","amadee","parent"], ["carolinerumble","amadee","parent"],
  ["andrewclemmer","moriahhalphin","spouse"],
  ["godfreyrumble","rebeccavarner","spouse"],
  ["godfreyrumble","carolinerumble","parent"], ["rebeccavarner","carolinerumble","parent"],
  ["henrywilkins","marycwilkins","spouse"],
  ["henrywilkins","elizwilkins","parent"], ["marycwilkins","elizwilkins","parent"],
  ["elizablaney","henrywilkins","parent"],
  ["johndunham","rebeccadewalt","spouse"],
  ["johndunham","martindunham","parent"], ["rebeccadewalt","martindunham","parent"],
  ["johndunham","johndunhamjr","parent",true], ["rebeccadewalt","johndunhamjr","parent",true],
  ["martindunhamsr","elizabethdunham","spouse"],
  ["martindunhamsr","johndunham","parent",true], ["elizabethdunham","johndunham","parent",true],
  ["wmgmiller","idaemme","spouse"],
  ["wmgmiller","emmamiller","parent"], ["idaemme","emmamiller","parent"],
  ["andrewclemmer","lebius","parent"], ["moriahhalphin","lebius","parent"],
  ["wbclemmer","phyllisclemmer","parent"],
  ["mbdunham","phyllisclemmer","parent"],
  ["wbclemmer","jacquelineclemmer","parent"],
  ["mbdunham","jacquelineclemmer","parent"],
  ["wbclemmer","bernardclemmer","parent"],
  ["mbdunham","bernardclemmer","parent"],
  ["amadee","graceclemmer","parent"],
  ["elizwilkins","graceclemmer","parent"],
  ["amadee","ireneclemmer","parent"],
  ["elizwilkins","ireneclemmer","parent"],
  ["amadee","bruceclemmer","parent"],
  ["elizwilkins","bruceclemmer","parent"],
  ["martindunham","pauldunham","parent"],
  ["emmamiller","pauldunham","parent"],
  ["martindunham","herbertdunham","parent"],
  ["emmamiller","herbertdunham","parent"],
  ["martindunham","clarencedunham","parent"],
  ["emmamiller","clarencedunham","parent"],
  ["martindunham","eleanoredunham","parent"],
  ["emmamiller","eleanoredunham","parent"],
  ["martindunham","harrydunham","parent"],
  ["emmamiller","harrydunham","parent"],
  ["martindunham","franklindunham","parent"],
  ["emmamiller","franklindunham","parent"],
  ["martindunham","edithdunham","parent"],
  ["emmamiller","edithdunham","parent"],
  ["martindunham","pearldunham","parent"],
  ["emmamiller","pearldunham","parent"],
  ["lebius","jasperEclemmer","parent"],
  ["carolinerumble","jasperEclemmer","parent"],
  ["lebius","elleclemmer","parent"],
  ["carolinerumble","elleclemmer","parent"],
  ["lebius","ionaclemmer","parent"],
  ["carolinerumble","ionaclemmer","parent"],
  ["lebius","josephclemmer","parent"],
  ["carolinerumble","josephclemmer","parent"],
  ["lebius","oliverclemmer","parent"],
  ["carolinerumble","oliverclemmer","parent"],
  ["henrywilkins","minervawilkins","parent"],
  ["marycwilkins","minervawilkins","parent"],
  ["henrywilkins","melendawilkins","parent"],
  ["marycwilkins","melendawilkins","parent"],
  ["henrywilkins","harveywilkins","parent"],
  ["marycwilkins","harveywilkins","parent"],
  ["henrywilkins","maggiewilkins","parent"],
  ["marycwilkins","maggiewilkins","parent"],
  ["henrywilkins","chaswilkins","parent"],
  ["marycwilkins","chaswilkins","parent"],
  ["andrewclemmer","jacobclemmer","parent"],
  ["moriahhalphin","jacobclemmer","parent"],
  ["andrewclemmer","delilaclemmer","parent"],
  ["moriahhalphin","delilaclemmer","parent"],
  ["andrewclemmer","jasperclemmer1840","parent"],
  ["moriahhalphin","jasperclemmer1840","parent"],
  ["andrewclemmer","michaelclemmer","parent"],
  ["moriahhalphin","michaelclemmer","parent"],
  ["andrewclemmer","minervaclemmer","parent"],
  ["moriahhalphin","minervaclemmer","parent"],
  ["andrewclemmer","margaretclemmer","parent"],
  ["moriahhalphin","margaretclemmer","parent"],
  ["andrewclemmer","barbaryclemmer","parent"],
  ["moriahhalphin","barbaryclemmer","parent"],
  ["elizablaney","hannahwilkins","parent"],
  ["elizablaney","williamwilkins","parent"],
  ["elizablaney","elizajwilkins","parent"],
  ["johnhblaney","elizablaney","spouse"],
  ["elizablaney","isaacblaney","parent"],
  ["johnhblaney","isaacblaney","parent"],
  ["elizablaney","joannablaney","parent"],
  ["johnhblaney","joannablaney","parent"],
  ["elizablaney","jonathanblaney","parent"],
  ["johnhblaney","jonathanblaney","parent"],
  ["elizablaney","phebeblaney","parent"],
  ["johnhblaney","phebeblaney","parent"],
];

// ---------- Notable events ----------
// Only moments a stranger would recognise without knowing the family, and only where a
// record puts this person in them (not where it merely could have).
const EVENTS = {
  henrywilkins: { tag:"The Civil War, 1861–1865",
    text:"Henry served for the Union in Company C of the 3rd West Virginia Infantry, a Preston County company raised in 1861, which was remounted as the 6th West Virginia Cavalry in 1864. His stepfather, John H. Blaney, served in the same company. Henry drew an invalid pension for his service from 1889, and his widow Mary drew it after him." },
  michaelclemmer: { tag:"The Battle of Cold Harbor, 1864",
    text:"Michael enlisted in March 1864 in Company K of the 116th Pennsylvania, a regiment of the Irish Brigade in Grant's Overland Campaign. He was killed on 3 June 1864 in the great frontal assault at Cold Harbor, Virginia, where the Union lost thousands of men in less than an hour, and is buried in Cold Harbor National Cemetery." },
  wbclemmer: { tag:"The Great Depression and the WPA, 1940",
    text:"When he registered for the draft in October 1940, William, 32, gave his employer as the W.P.A., the Works Progress Administration, the New Deal's programme of public-works jobs for the unemployed, working at Smithfield R.D. 3. By 1950 he was running a coal mine of his own." },
};
const EVENT_YEAR = {};   // tag → year, for a tag with no year in it
const EVENT_PLACE = {    // tag → [place keys] the map flies to
  "The Great Depression and the WPA, 1940": ["smithfield"],
  "The Battle of Cold Harbor, 1864": ["coldharbor"],
};

// ---------- Generations ----------
// 0 is the family today; parents 1, grandparents 2, and so on back. Provisional until the
// seed fixes who stands in generation zero; add bands as the tree deepens.
const GEN_LABELS = {
  0: ["The family today", ""],
  1: ["Parents", "b. 1940s"],
  2: ["Grandparents", "b. 1900s–1910s"],
  3: ["Great-grandparents", "b. 1860s–80s"],
  4: ["2× great-grandparents", "b. 1830s–40s"],
  5: ["3× great-grandparents", "b. c. 1810s"],
};

// ---------- Layout hints ----------
const LAYOUT_LINE = {};  // person id → line whose column they sit in (in-laws beside a spouse)
const LAYOUT_X = {       // person id → fixed column, a fraction of the width
  // Each sibling group sits beside its direct-line member; each couple's parents sit above
  // them in the same left-to-right order, Clemmer side left, Dunham side right.
  // gen 5
  andrewclemmer:0.14, moriahhalphin:0.20, godfreyrumble:0.30, rebeccavarner:0.35,
  elizablaney:0.47, johnhblaney:0.53,
  // gen 4
  jacobclemmer:0.02, delilaclemmer:0.04, jasperclemmer1840:0.06, michaelclemmer:0.08,
  minervaclemmer:0.10, margaretclemmer:0.12, barbaryclemmer:0.14,
  lebius:0.20, carolinerumble:0.32,
  hannahwilkins:0.39, williamwilkins:0.41, elizajwilkins:0.43, henrywilkins:0.46, marycwilkins:0.50,
  isaacblaney:0.54, joannablaney:0.56, jonathanblaney:0.58, phebeblaney:0.60,
  johndunham:0.70, martindunhamsr:0.72, elizabethdunham:0.78, johndunhamjr:0.66, rebeccadewalt:0.76, wmgmiller:0.84, idaemme:0.90,
  // gen 3
  jasperEclemmer:0.08, elleclemmer:0.11, ionaclemmer:0.14, josephclemmer:0.17, oliverclemmer:0.20,
  amadee:0.25, elizwilkins:0.42,
  minervawilkins:0.46, melendawilkins:0.49, harveywilkins:0.52, maggiewilkins:0.55, chaswilkins:0.58,
  martindunham:0.72, emmamiller:0.86,
  // gen 2
  graceclemmer:0.22, ireneclemmer:0.26, bruceclemmer:0.30,
  pauldunham:0.66, herbertdunham:0.70, clarencedunham:0.74, eleanoredunham:0.78,
  harrydunham:0.82, franklindunham:0.86, edithdunham:0.90, pearldunham:0.94,
  // gen 1
  phyllisclemmer:0.28, jacquelineclemmer:0.32, bernardclemmer:0.36, neildunham:0.50,
};

// ---------- Map ----------
// PLACES: key → { n, lat, lon }. GEO: person id → { b, bEst, d, dEst, stops:[{p, y, e}] };
// e:1 (and bEst/dEst) marks an estimated year, drawn as a dashed arc.
const PLACES = {
  pointmarion: { n:"Point Marion, Fayette Co., PA", lat:39.7387, lon:-79.8998 },
  springhill: { n:"Springhill Twp., Fayette Co., PA", lat:39.7480, lon:-79.8350 },
  smithfield: { n:"Smithfield, Fayette Co., PA", lat:39.8012, lon:-79.8084 },
  cheathaven: { n:"Cheat Haven, Fayette Co., PA", lat:39.7195, lon:-79.8540 },
  morgantown: { n:"Morgantown, Monongalia Co., WV", lat:39.6295, lon:-79.9559 },
  coldharbor: { n:"Cold Harbor, Hanover Co., VA", lat:37.5871, lon:-77.2861 },
  mtlakepark: { n:"Mountain Lake Park, Garrett Co., MD", lat:39.3987, lon:-79.3817 },
  masontownwv: { n:"Masontown, Preston Co., WV", lat:39.5498, lon:-79.7959 },
};
const GEO = {
  wbclemmer: { b:1908, bEst:0, d:1982, dEst:0, stops:[ {p:"pointmarion", y:1908, e:0}, {p:"springhill", y:1910, e:0}, {p:"pointmarion", y:1982, e:1} ] },
  neildunham: { b:1935, bEst:0, d:2021, dEst:0, stops:[ {p:"springhill", y:1935, e:1}, {p:"mtlakepark", y:2021, e:1} ] },
  mbdunham: { b:1916, bEst:0, d:1979, dEst:0, stops:[ {p:"smithfield", y:1916, e:0}, {p:"springhill", y:1938, e:1}, {p:"pointmarion", y:1979, e:1} ] },
  amadee: { b:1880, bEst:0, d:1921, dEst:0, stops:[ {p:"springhill", y:1880, e:0}, {p:"cheathaven", y:1907, e:0}, {p:"springhill", y:1910, e:0} ] },
  elizwilkins: { b:1884, bEst:0, d:1931, dEst:0, stops:[ {p:"morgantown", y:1884, e:0}, {p:"springhill", y:1900, e:0} ] },
  henrywilkins: { b:1841, bEst:0, d:1913, dEst:0, stops:[ {p:"masontownwv", y:1841, e:1}, {p:"springhill", y:1881, e:1}, {p:"morgantown", y:1884, e:0}, {p:"springhill", y:1900, e:0} ] },
  marycwilkins: { b:1845, bEst:0, d:1927, dEst:0, stops:[ {p:"masontownwv", y:1845, e:0}, {p:"springhill", y:1881, e:1}, {p:"morgantown", y:1884, e:0}, {p:"springhill", y:1900, e:0} ] },
  elizablaney: { b:1815, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1815, e:1} ] },
  andrewclemmer: { b:1810, bEst:1, d:1880, dEst:1, stops:[ {p:"springhill", y:1810, e:1} ] },
  moriahhalphin: { b:1812, bEst:1, d:1860, dEst:1, stops:[ {p:"springhill", y:1812, e:1} ] },
  lebius: { b:1832, bEst:0, d:1909, dEst:0, stops:[ {p:"springhill", y:1832, e:1} ] },
  carolinerumble: { b:1841, bEst:0, d:1909, dEst:0, stops:[ {p:"springhill", y:1841, e:1} ] },
  martindunham: { b:1863, bEst:0, d:1943, dEst:0, stops:[ {p:"springhill", y:1863, e:1}, {p:"smithfield", y:1900, e:0}, {p:"springhill", y:1943, e:1} ] },
  emmamiller: { b:1881, bEst:0, d:1942, dEst:0, stops:[ {p:"smithfield", y:1881, e:1} ] },
  bernardclemmer: { b:1946, bEst:0, d:2003, dEst:0, stops:[ {p:"springhill", y:1946, e:1} ] },
  graceclemmer: { b:1910, bEst:0, d:1979, dEst:0, stops:[ {p:"springhill", y:1910, e:0} ] },
  ireneclemmer: { b:1912, bEst:0, d:1952, dEst:0, stops:[ {p:"springhill", y:1912, e:1} ] },
  bruceclemmer: { b:1917, bEst:0, d:1987, dEst:0, stops:[ {p:"springhill", y:1917, e:1} ] },
  pauldunham: { b:1909, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1909, e:1} ] },
  herbertdunham: { b:1911, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1911, e:1} ] },
  clarencedunham: { b:1913, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1913, e:1} ] },
  eleanoredunham: { b:1915, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1915, e:1} ] },
  harrydunham: { b:1917, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1917, e:1} ] },
  franklindunham: { b:1920, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1920, e:1} ] },
  edithdunham: { b:1921, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1921, e:1} ] },
  pearldunham: { b:1923, bEst:1, d:1930, dEst:1, stops:[ {p:"smithfield", y:1923, e:1} ] },
  jasperEclemmer: { b:1862, bEst:0, d:1931, dEst:0, stops:[ {p:"springhill", y:1862, e:1}, {p:"cheathaven", y:1909, e:0}, {p:"springhill", y:1931, e:0} ] },
  elleclemmer: { b:1866, bEst:1, d:1880, dEst:1, stops:[ {p:"springhill", y:1866, e:1} ] },
  ionaclemmer: { b:1868, bEst:0, d:1954, dEst:0, stops:[ {p:"springhill", y:1868, e:1} ] },
  josephclemmer: { b:1872, bEst:0, d:1959, dEst:0, stops:[ {p:"springhill", y:1872, e:1} ] },
  oliverclemmer: { b:1877, bEst:1, d:1880, dEst:1, stops:[ {p:"springhill", y:1877, e:1} ] },
  minervawilkins: { b:1874, bEst:1, d:1900, dEst:1, stops:[ {p:"springhill", y:1874, e:1} ] },
  melendawilkins: { b:1876, bEst:0, d:1900, dEst:1, stops:[ {p:"masontownwv", y:1876, e:1}, {p:"springhill", y:1900, e:0} ] },
  harveywilkins: { b:1878, bEst:0, d:1937, dEst:0, stops:[ {p:"masontownwv", y:1878, e:1}, {p:"springhill", y:1900, e:0} ] },
  maggiewilkins: { b:1881, bEst:0, d:1900, dEst:1, stops:[ {p:"springhill", y:1881, e:1} ] },
  chaswilkins: { b:1891, bEst:0, d:1900, dEst:1, stops:[ {p:"springhill", y:1891, e:1} ] },
  jacobclemmer: { b:1835, bEst:1, d:1850, dEst:1, stops:[ {p:"springhill", y:1835, e:1} ] },
  delilaclemmer: { b:1838, bEst:1, d:1850, dEst:1, stops:[ {p:"springhill", y:1838, e:1} ] },
  michaelclemmer: { b:1842, bEst:0, d:1864, dEst:0, stops:[ {p:"springhill", y:1842, e:1}, {p:"coldharbor", y:1864, e:0} ] },
  minervaclemmer: { b:1844, bEst:1, d:1850, dEst:1, stops:[ {p:"springhill", y:1844, e:1} ] },
  margaretclemmer: { b:1845, bEst:1, d:1850, dEst:1, stops:[ {p:"springhill", y:1845, e:1} ] },
  barbaryclemmer: { b:1848, bEst:1, d:1850, dEst:1, stops:[ {p:"springhill", y:1848, e:1} ] },
  frankclemmer:0.16, jasperclemmer1840: { b:1840, bEst:0, d:1922, dEst:0, stops:[ {p:"springhill", y:1840, e:1} ] },
  hannahwilkins: { b:1834, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1834, e:1} ] },
  williamwilkins: { b:1838, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1838, e:1} ] },
  elizajwilkins: { b:1844, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1844, e:1} ] },
  johnhblaney: { b:1821, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1821, e:1} ] },
  isaacblaney: { b:1847, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1847, e:1} ] },
  joannablaney: { b:1850, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1850, e:1} ] },
  jonathanblaney: { b:1853, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1853, e:1} ] },
  phebeblaney: { b:1856, bEst:1, d:1860, dEst:1, stops:[ {p:"masontownwv", y:1856, e:1} ] },
  frankclemmer: { b:1853, bEst:0, d:1934, dEst:0, stops:[ {p:"springhill", y:1853, e:1}, {p:"cheathaven", y:1909, e:1} ] },
  johndunham: { b:1830, bEst:1, d:1899, dEst:1, stops:[ {p:"springhill", y:1850, e:0} ] },
  rebeccadewalt: { b:1834, bEst:1, d:1899, dEst:1, stops:[ {p:"springhill", y:1860, e:0} ] },
  johndunhamjr: { b:1859, bEst:1, d:1889, dEst:1, stops:[ {p:"springhill", y:1859, e:1} ] },
  martindunhamsr: { b:1803, bEst:1, d:1860, dEst:1, stops:[ {p:"springhill", y:1850, e:0} ] },
  elizabethdunham: { b:1805, bEst:1, d:1860, dEst:1, stops:[ {p:"springhill", y:1850, e:0} ] },
};
// The map's opening frame, [[west, south], [east, north]] in degrees: southwestern
// Pennsylvania and the West Virginia line, until the records reach further.
const MAP_FRAME = [[-81.5, 37.3], [-76.9, 41.0]];

if (typeof module !== "undefined") module.exports = {
  SITE, LINES, S, P, E, EVENTS, EVENT_YEAR, EVENT_PLACE, GEN_LABELS, LAYOUT_LINE, LAYOUT_X,
  PLACES, GEO, MAP_FRAME,
};
